services:
  server:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - network
    depends_on:
      minio:
        condition: service_healthy

  minio:
    container_name: minio
    image: quay.io/minio/minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "ResearchSonics"
      MINIO_ROOT_PASSWORD: "ResearchSonics"
    volumes:
      - minio_data:/data
    networks:
      - network
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
    command: server --console-address ":9001" /templates

volumes:
  minio_data:

networks:
  network:
    driver: bridge
